version: '3'
services:
  database:
    image: postgres:12.11-alpine
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test-task
