spring:
  datasource:
    url: jdbc:postgresql://{MESH_GROUP_TEST_TASK_DATASOURCE_HOST}:{MESH_GROUP_TEST_TASK_DATASOURCE_PORT}/{MESH_GROUP_TEST_TASK_DATASOURCE_NAME}
    username: {MESH_GROUP_TEST_TASK_DATASOURCE_USERNAME}
    password: {MESH_GROUP_TEST_TASK_DATASOURCE_PASSWORD}
